name: newtify
version: 1.2.3
description: >-
  Have you been turned into a newt?  Would you like to be?
  This package can help. It has all of the
  newt-transmogrification functionality you have been looking
  for.
author: Natalie Weizenbaum <nweiz@google.com>
homepage: https://newtify.dartlang.org
documentation: https://docs.newtify.com
dev_dependencies:
  # ···
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0