name: websocket_rd
version: 1.0.0
description: remote_desctiop
author: Natalie Weizenbaum <riku@tanide.net>
dev_dependencies:
  # ···
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  skyway_interop:
    git: git://github.com/rikuTanide/skyway_interop.git